import { run } from '../src/utils.ts'
import { Select } from 'cliffy/prompt/mod.ts'
import * as semver from 'semver/mod.ts'
import { config } from './utils.ts'

const inc = (type: semver.ReleaseType) => semver.inc(config.version, type)

const types: semver.ReleaseType[] = ['patch', 'minor', 'major']

const options = types.map((type) => ({
  name: `${type}(${inc(type)})`,
  value: type,
}))

await run('yarn', 'test')

const releaseType = await Select.prompt({
  message: 'Please select release type',
  options: options,
})

const releaseVersion = inc(releaseType as semver.ReleaseType)

await Deno.writeTextFile(
  'version.ts',
  `// Do not edit this file directly.
// This file is Auto generate by scripts/release.ts

export const version = '${releaseVersion}'
`,
)

await run('git', 'add', 'version.ts')

await run(
  'yarn',
  'version',
  `--${releaseType}`,
  '--message',
  `chore: release ${releaseVersion}`,
)

await run('git', 'push')
await run('git', 'push', '--tags')
