import { run } from '../src/utils.ts'
import { Select } from 'cliffy/prompt/mod.ts'
import * as semver from 'semver/mod.ts'
import { join } from 'path/mod.ts'

const pkgPath = join(Deno.cwd(), 'package.json')

const pkgConf = await getPkgConfig<IConfig>()

const inc = (type: semver.ReleaseType) => semver.inc(pkgConf.version, type)

const types: semver.ReleaseType[] = ['patch', 'minor', 'major']

const options = types.map((type) => ({
  name: `${type}(${inc(type)})`,
  value: type,
}))

await run('x', 'run', 'test')

const releaseType = (await Select.prompt({
  message: 'Please select release type',
  options: options,
})) as semver.ReleaseType

const releaseVersion = inc(releaseType)

if (!releaseVersion) {
  Deno.exit()
}

await Deno.writeTextFile(
  'version.ts',
  `// Do not edit this file directly.
// This file is Auto generate by scripts/release.ts

export const version = '${releaseVersion}'
`,
)

await run('git', 'add', 'version.ts')

await modifyPackageVersion(releaseVersion)
await run('git', 'add', 'package.json')

await run('git', 'commit', '-m', `chore: release ${releaseVersion}`)
await run('git', 'tag', `v${releaseVersion}`)

await run('git', 'push')
await run('git', 'push', '--tags')

// --------

async function modifyPackageVersion(version: string) {
  pkgConf.version = version

  await Deno.writeTextFile(pkgPath, JSON.stringify(pkgConf, null, 2))
}

async function getPkgConfig<T>(): Promise<T> {
  const fileContent = await Deno.readTextFile(pkgPath)

  return JSON.parse(fileContent)
}

interface IConfig {
  version: string
}
