name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    # disabled for now
    if: ${{ false }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm i

      - run: pnpm run test

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ false }}
        with:
          files: ./coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: false
